on:
  push:
  
jobs:
   train-model:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Install dependencies
          pip install -r requirements.txt
          dvc pull
          dvc repro
          dvc push
          cml pr --squash --skip-ci .
          ### Create CML report ###
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          done
          ########################
          
          cml send-comment --pr --update report.md
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          done
          ########################
          

          cml send-comment --pr --update report.md)

