on:
  push:
  
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    environment: cloud
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::175754385727:role/SandboxUser
      - name: cml runner
        env:
          # set these secrets via gh CLI or UI. See also:
          # https://cml.dev/doc/self-hosted-runners?tab=GitHub#personal-access-token
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner \
              --log="debug" \
              --cloud=aws \
              --cloud-region=us-east-1 \
              --cloud-type=t2.large \
              --cloud-startup-script=$(##!/bin/bash
              set -e
              mkdir -p runner/{work/_temp,work/_tool/Python/3.9.18/x64}
              wget -O- https://github.com/actions/python-versions/releases/download/3.9.18-5997508477/python-3.9.18-linux-22.04-x64.tar.gz | tar xzf - -C runner/work/_temp/ 
              cd /home/runner/work/_tool/Python/3.9.18/x64 |  base64 -d) \
              --labels=cml-runner


