on:
  push:
  
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    environment: cloud
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::175754385727:role/SandboxUser
      - name: cml runner
        env:
          # set these secrets via gh CLI or UI. See also:
          # https://cml.dev/doc/self-hosted-runners?tab=GitHub#personal-access-token
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner \
              --log="debug" \
              --cloud=aws \
              --cloud-region=us-east-1 \
              --cloud-type=t2.large \
              --cloud-startup-script=IyEvYmluL2Jhc2gKc2V0IC1lCm1rZGlyIC1wIGFjdGlvbnMtcnVubmVyL3tfd29yay9fdGVtcCxfd29yay9fdG9vbH0Kd2dldCAtTy0gaHR0cHM6Ly9naXRodWIuY29tL2FjdGlvbnMvcHl0aG9uLXZlcnNpb25zL3JlbGVhc2VzL2Rvd25sb2FkLzMuOS4xOC01OTk3NTA4NDc3L3B5dGhvbi0zLjkuMTgtbGludXgtMjIuMDQteDY0LnRhci5neiB8IHRhciB4emYgLSAtQyBhY3Rpb25zLXJ1bm5lci9fd29yay9fdGVtcC8KZXhwb3J0IExEX0xJQlJBUllfUEFUSD0iL2hvbWUvdWJ1bnR1L2FjdGlvbnMtcnVubmVyL193b3JrL190b29sL1B5dGhvbi8zLjkuMTgveDY0L2xpYjovUHl0aG9uLzMuOS4xOC94NjQvbGliOiRMRF9MSUJSQVJZX1BBVEgiCm1rZGlyIC1wIC9ob21lL3VidW50dS9hY3Rpb25zLXJ1bm5lci9fd29yay9fdG9vbC9QeXRob24vMy45LjE4L3g2NApjcCAtUiBhY3Rpb25zLXJ1bm5lci9fd29yay9fdGVtcC8qIC9ob21lL3VidW50dS9hY3Rpb25zLXJ1bm5lci9fd29yay9fdG9vbC9QeXRob24vMy45LjE4L3g2NApybSAvaG9tZS91YnVudHUvYWN0aW9ucy1ydW5uZXIvX3dvcmsvX3Rvb2wvUHl0aG9uLzMuOS4xOC94NjQvc2V0dXAuc2gKY2QgL2hvbWUvdWJ1bnR1L2FjdGlvbnMtcnVubmVyL193b3JrL190b29sL1B5dGhvbi8zLjkuMTgveDY0CmxuIC1zIC4vYmluL3B5dGhvbjMuOSBweXRob24KY2QgYmluLwpsbiAtcyBweXRob24zLjkgcHl0aG9uMzkKbG4gLXMgcHl0aG9uMy45IHB5dGhvbgpjaG1vZCAreCBweXRob24zLjkgcHl0aG9uMzkgcHl0aG9uCi4vcHl0aG9uIC1tIGVuc3VyZXBpcAouL3B5dGhvbiAtbSBwaXAgaW5zdGFsbCAtLWlnbm9yZS1pbnN0YWxsZWQgcGlwIC0tZGlzYWJsZS1waXAtdmVyc2lvbi1jaGVjayAtLW5vLXdhcm4tc2NyaXB0LWxvY2F0aW9uIC0tcm9vdC11c2VyLWFjdGlvbj1pZ25vcmU= \
              --labels=cml-runner
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container:
      image: python:3.9
    environment: cloud
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v2
        with:
            python-version: "3.9"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::175754385727:role/SandboxUser
      - name: cml setup
        run: cml ci
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: dvc-repro-cml
        env:
          # set these secrets via gh CLI or UI. See also:
          # https://cml.dev/doc/self-hosted-runners?tab=GitHub#personal-access-token
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Install dependencies
          pip install -r requirements.txt
          dvc pull
          dvc repro
          dvc push
          cml pr --squash --skip-ci .
          ### Create CML report ###
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          done
          ########################
          
          cml send-comment --pr --update report.md
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          done
          ########################
          

          cml send-comment --pr --update report.md  
