on:
  push:
  
jobs:
  train-model:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    environment: cloud
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::175754385727:role/SandboxUser
      - name: CML setup
        run: cml ci
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: DVC repro
        run: |
          source venv/bin/activate
          dvc pull
          dvc repro
          dvc push
          cml pr --squash --skip-ci .
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          cml send-comment --pr --update report.md
      - name: Clean up virtual environment
        run: deactivate

