on:
  push:
  
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    environment: cloud
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::175754385727:role/SandboxUser
      - name: cml runner
        env:
          # set these secrets via gh CLI or UI. See also:
          # https://cml.dev/doc/self-hosted-runners?tab=GitHub#personal-access-token
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner \
              --log="debug" \
              --cloud=aws \
              --cloud-region=us-east-1 \
              --cloud-type=t2.large \
              --cloud-startup-script=IyEvYmluL2Jhc2gKc2V0IC1lCm1rZGlyIC1wIGFjdGlvbnMtcnVubmVyICYmIGNkIGFjdGlvbnMtcnVubmVyCm1rZGlyIC1wIF93b3JrL190ZW1wCm1rZGlyIC1wIF93b3JrL190b29sCndnZXQgaHR0cHM6Ly9naXRodWIuY29tL2FjdGlvbnMvcHl0aG9uLXZlcnNpb25zL3JlbGVhc2VzL2Rvd25sb2FkLzMuOS4xOC01OTk3NTA4NDc3L3B5dGhvbi0zLjkuMTgtbGludXgtMjIuMDQteDY0LnRhci5negp0YXIgeHpmIHB5dGhvbi0zLjkuMTgtbGludXgtMjIuMDQteDY0LnRhci5neiAtQyAgX3dvcmsvX3RlbXAvCmNkIF93b3JrL190ZW1wLwoKZXhwb3J0IExEX0xJQlJBUllfUEFUSD0vaG9tZS91YnVudHUvYWN0aW9ucy1ydW5uZXIvX3dvcmsvX3Rvb2wvUHl0aG9uLzMuOS4xOC94NjQvbGliOi9QeXRob24vMy45LjE4L3g2NC9saWI6JExEX0xJQlJBUllfUEFUSAoKUFlUSE9OX0ZVTExfVkVSU0lPTj0iMy45LjE4IgpNQUpPUl9WRVJTSU9OPSQoZWNobyAkUFlUSE9OX0ZVTExfVkVSU0lPTiB8IGN1dCAtZCAnLicgLWYgMSkKTUlOT1JfVkVSU0lPTj0kKGVjaG8gJFBZVEhPTl9GVUxMX1ZFUlNJT04gfCBjdXQgLWQgJy4nIC1mIDIpCgpQWVRIT05fTUFKT1I9cHl0aG9uJE1BSk9SX1ZFUlNJT04KUFlUSE9OX01BSk9SX0RPVF9NSU5PUj1weXRob24kTUFKT1JfVkVSU0lPTi4kTUlOT1JfVkVSU0lPTgpQWVRIT05fTUFKT1JNSU5PUj1weXRob24kTUFKT1JfVkVSU0lPTiRNSU5PUl9WRVJTSU9OCgpBR0VOVF9UT09MU0RJUkVDVE9SWT0iL2hvbWUvdWJ1bnR1L2FjdGlvbnMtcnVubmVyL193b3JrL190b29sIgppZiBbIC16ICR7QUdFTlRfVE9PTFNESVJFQ1RPUlkreH0gXTsgdGhlbgogICAgIyBObyBBR0VOVF9UT09MU0RJUkVDVE9SWSBvbiBHaXRIdWIgaW1hZ2VzCiAgICBUT09MQ0FDSEVfUk9PVD0kUlVOTkVSX1RPT0xfQ0FDSEUKZWxzZQogICAgVE9PTENBQ0hFX1JPT1Q9JEFHRU5UX1RPT0xTRElSRUNUT1JZCmZpCgpQWVRIT05fVE9PTENBQ0hFX1BBVEg9JFRPT0xDQUNIRV9ST09UL1B5dGhvbgpQWVRIT05fVE9PTENBQ0hFX1ZFUlNJT05fUEFUSD0kUFlUSE9OX1RPT0xDQUNIRV9QQVRILyRQWVRIT05fRlVMTF9WRVJTSU9OClBZVEhPTl9UT09MQ0FDSEVfVkVSU0lPTl9BUkNIX1BBVEg9JFBZVEhPTl9UT09MQ0FDSEVfVkVSU0lPTl9QQVRIL3g2NAoKZWNobyAiQ2hlY2sgaWYgUHl0aG9uIGhvc3RlZHRvb2xjYWNoZSBmb2xkZXIgZXhpc3QuLi4iCmlmIFsgISAtZCAkUFlUSE9OX1RPT0xDQUNIRV9QQVRIIF07IHRoZW4KICAgIGVjaG8gIkNyZWF0aW5nIFB5dGhvbiBob3N0ZWR0b29sY2FjaGUgZm9sZGVyLi4uIgogICAgbWtkaXIgLXAgJFBZVEhPTl9UT09MQ0FDSEVfUEFUSAplbGlmIFsgLWQgJFBZVEhPTl9UT09MQ0FDSEVfVkVSU0lPTl9QQVRIIF07IHRoZW4KICAgIGVjaG8gIkRlbGV0aW5nIFB5dGhvbiAkUFlUSE9OX0ZVTExfVkVSU0lPTiIKICAgIHJtIC1yZiAkUFlUSE9OX1RPT0xDQUNIRV9WRVJTSU9OX1BBVEgKZmkKCmVjaG8gIkNyZWF0ZSBQeXRob24gJFBZVEhPTl9GVUxMX1ZFUlNJT04gZm9sZGVyIgpta2RpciAtcCAkUFlUSE9OX1RPT0xDQUNIRV9WRVJTSU9OX0FSQ0hfUEFUSAoKZWNobyAiQ29weSBQeXRob24gYmluYXJpZXMgdG8gaG9zdGVkdG9vbGNhY2hlIGZvbGRlciIKY3AgLVIgLi8qICRQWVRIT05fVE9PTENBQ0hFX1ZFUlNJT05fQVJDSF9QQVRICnJtICRQWVRIT05fVE9PTENBQ0hFX1ZFUlNJT05fQVJDSF9QQVRIL3NldHVwLnNoCgpjZCAkUFlUSE9OX1RPT0xDQUNIRV9WRVJTSU9OX0FSQ0hfUEFUSAoKZWNobyAiQ3JlYXRlIGFkZGl0aW9uYWwgc3ltbGlua3MgKFJlcXVpcmVkIGZvciB0aGUgVXNlUHl0aG9uVmVyc2lvbiBBenVyZSBQaXBlbGluZXMgdGFzayBhbmQgdGhlIHNldHVwLXB5dGhvbiBHaXRIdWIgQWN0aW9uKSIKbG4gLXMgLi9iaW4vJFBZVEhPTl9NQUpPUl9ET1RfTUlOT1IgcHl0aG9uCgpjZCBiaW4vCmxuIC1zICRQWVRIT05fTUFKT1JfRE9UX01JTk9SICRQWVRIT05fTUFKT1JNSU5PUgppZiBbICEgLWYgcHl0aG9uIF07IHRoZW4KICAgIGxuIC1zICRQWVRIT05fTUFKT1JfRE9UX01JTk9SIHB5dGhvbgpmaQoKY2htb2QgK3ggLi4vcHl0aG9uICRQWVRIT05fTUFKT1IgJFBZVEhPTl9NQUpPUl9ET1RfTUlOT1IgJFBZVEhPTl9NQUpPUk1JTk9SIHB5dGhvbgoKZWNobyAiVXBncmFkaW5nIHBpcC4uLiIKLi9weXRob24gLW0gZW5zdXJlcGlwCi4vcHl0aG9uIC1tIHBpcCBpbnN0YWxsIC0taWdub3JlLWluc3RhbGxlZCBwaXAgLS1kaXNhYmxlLXBpcC12ZXJzaW9uLWNoZWNrIC0tbm8td2Fybi1zY3JpcHQtbG9jYXRpb24gLS1yb290LXVzZXItYWN0aW9uPWlnbm9yZQoKZWNobyAiQ3JlYXRlIGNvbXBsZXRlIGZpbGUiCnRvdWNoICRQWVRIT05fVE9PTENBQ0hFX1ZFUlNJT05fUEFUSC94NjQuY29tcGxldGU= \
              --labels=cml-runner
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container:
      image: python:3.9
    environment: cloud
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v2
        with:
            python-version: "3.9"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::175754385727:role/SandboxUser
      - name: cml setup
        run: cml ci
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: dvc-repro-cml
        env:
          # set these secrets via gh CLI or UI. See also:
          # https://cml.dev/doc/self-hosted-runners?tab=GitHub#personal-access-token
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Install dependencies
          pip install -r requirements.txt
          dvc pull
          dvc repro
          dvc push
          cml pr --squash --skip-ci .
          ### Create CML report ###
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          done
          ########################
          
          cml send-comment --pr --update report.md
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          done
          ########################
          

          cml send-comment --pr --update report.md  
