on:
  push:

jobs:
  build:
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2
      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
