on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: otmane10/customer-booking:0.0.1
    steps:

      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Print Python version
        run: ls
          
